/* automatically generated by rust-bindgen 0.66.1 */

extern "C" {
    pub fn Hello() -> ::core::ffi::c_int;
}
extern "C" {
    pub fn Max() -> ::core::ffi::c_int;
}
extern "C" {
    pub fn max(num1: ::core::ffi::c_int, num2: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
